---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: hello-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-flask-app
  template:
    metadata:
      labels:
        app: hello-flask-app
    spec:
      containers:
        - name: hello-flask-app
          image: matthewdavis111/hello-flask-app
          ports:
            - containerPort: 5000
