apiVersion: v1
kind: Pod
metadata:
    name: hello-flask-app
spec:
    containers: 
    - name: hello-flask-app
      image: matthewdavis111/hello-flask-app
      ports:
      - name: web
        containerPort: 5000