---
apiVersion: v1
kind: Service
metadata:
  name: hello-dotnet-core-service
spec:
  selector:
    app: hello-dotnet-core-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer