---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    app: hello-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
        - name: hello-go
          image: matthewdavis111/hello-go
          ports:
            - containerPort: 8180